version: '3'

services:
  app:
    build:
      context: .
    container_name: Task_management_system
    depends_on:
    - db
    env_file:
      - .env
    ports:
      - '8080:8080'
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
