spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: task-management-sys
  datasource:
    url: jdbc:postgresql://${HOST}:${DB_PORT}/${POSTGRES_DB_NAME}?currentSchema=${CURRENT_DB_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        default_schema: ${CURRENT_DB_SCHEMA}
    generate-ddl: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    site.ph0en1x.task_management_sys: DEBUG
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1 #hours
    refresh: 30 #days
